const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const {rangePoints}=require('../src/lib/trends/model.ts');
const format=n=>new Intl.NumberFormat('zh-CN',{maximumFractionDigits:4}).format(n);
const BASE=process.env.TRENDS_BASE_URL||'http://127.0.0.1:4327';
(async()=>{
const browser=await chromium.launch({headless:true,executablePath:'/usr/bin/chromium',args:['--no-sandbox']});
for(const viewport of [{width:1440,height:1100},{width:390,height:844},{width:360,height:760}]){
const context=await browser.newContext({viewport});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(`${BASE}/trends/`);await page.locator('#chart-line[d]').waitFor();
const data=JSON.parse(await page.locator('#trend-data').textContent()),radish=data.find(i=>i.name==='白萝卜'),pork=data.find(i=>i.name==='猪肉'),porkWindow=rangePoints(pork.points,'1m'),radishLast=radish.points.at(-1),porkLast=pork.points.at(-1);
assert.equal(await page.locator('h1').count(),1);assert.ok(await page.locator('#market-rows tr').count()>=9);assert.doesNotMatch(await page.locator('#market-rows').textContent(),/28种蔬菜|6种水果/);
assert.equal(await page.locator('#instrument-title').textContent(),'黄瓜');assert.match(await page.locator('#instrument-symbol').textContent(),/全国/);assert.match(await page.locator('#frequency').textContent(),/周度/);assert.equal(await page.locator('#last-value').textContent(),format(data.find(i=>i.id==='cn-mofcom-224068').points.at(-1).value/2));
const category=async value=>viewport.width<=760?await page.locator('#category-select').selectOption(value):await page.locator(`[data-category="${value}"]`).click();
await page.locator('#market-rows tr').filter({hasText:'全国'}).locator('.instrument-link').filter({hasText:/^白萝卜$/}).click();
assert.equal(await page.locator('#last-value').textContent(),format(radishLast.value/2));assert.equal(await page.locator('#quote-range').isVisible(),false);assert.ok(data.every(i=>i.sourceKey!=='chaoyang'));
await page.locator('[data-range="all"]').click();assert.ok((await page.locator('#chart-caption').textContent()).startsWith(`${radish.points.length} 个观测值`));
await page.locator('[data-range="7d"]').click();assert.ok((await page.locator('#chart-caption').textContent()).startsWith(`${rangePoints(radish.points,'7d').length} 个观测值`));
await page.locator('[data-range="2p"]').click();assert.match(await page.locator('#chart-caption').textContent(),/2 个观测值/);
await page.locator('[data-range="1m"]').click();await page.locator('.instrument-link').filter({hasText:/^猪肉$/}).click();
assert.equal(await page.locator('#last-value').textContent(),format(porkLast.value/2));assert.equal(await page.locator('#instrument-unit').textContent(),'元/斤');
assert.match(await page.locator('#range-status').textContent(),/已选近1月/);
const porkCard=page.locator('#market-rows tr').filter({has:page.locator('.instrument-link').filter({hasText:/^猪肉$/})});
assert.equal(await porkCard.locator('.price-cell').textContent(),`${format(porkLast.value/2)} 元/斤`);
await page.locator('#point-slider').fill('0');assert.equal(await page.locator('#point-readout').textContent(),`${porkWindow[0].date} · ${format(porkWindow[0].value/2)} 元/斤`);
await page.locator('[data-unit="original"]').click();assert.equal(await page.locator('#last-value').textContent(),format(porkLast.value));assert.equal(await porkCard.locator('.price-cell').textContent(),`${format(porkLast.value)} 元/公斤`);
assert.equal(await page.locator('#point-readout').textContent(),`${porkWindow[0].date} · ${format(porkWindow[0].value)} 元/公斤`);assert.ok((await page.locator('#chart-labels').textContent()).includes(format(Math.max(...porkWindow.map(p=>p.value)))));
await page.locator('[data-unit="jin"]').click();assert.equal(await page.locator('#last-value').textContent(),format(porkLast.value/2));
await page.locator('[data-range="2p"]').click();assert.match(await page.locator('#chart-caption').textContent(),/2 个观测值/);assert.ok((await page.locator('#period-dates').textContent()).startsWith(pork.points.at(-2).date));
await page.locator('[data-range="72m"]').click();assert.equal(await page.locator('[data-range="72m"]').getAttribute('aria-pressed'),'true');assert.match(await page.locator('#range-status').textContent(),/已选近6年/);assert.ok((await page.locator('#chart-caption').textContent()).startsWith(`${rangePoints(pork.points,'72m').length} 个观测值`));
assert.match(await page.locator('#instrument-coverage').textContent(),/不是超市零售价/);await category('fx');
const first=await page.locator('#chart-line').getAttribute('d');await page.locator('[data-range="3m"]').click();assert.notEqual(await page.locator('#chart-line').getAttribute('d'),first);
await page.locator('#point-slider').fill('0');assert.match(await page.locator('#point-readout').textContent(),/CNY \/ USD/);
await page.locator('#detail-favorite').click();await page.reload();assert.equal(await page.locator('[data-unit="jin"]').getAttribute('aria-pressed'),'true');await category('all');await page.locator('#favorites-only').click();assert.equal(await page.locator('#market-rows tr').count(),1);await page.locator('#favorites-only').click();
await category('commodity');await page.locator('#trend-search').fill('电解铜');assert.equal(await page.locator('#instrument-unit').textContent(),'元/吨');assert.equal(await page.locator('#last-value').textContent(),format(data.find(i=>i.name==='电解铜（1#）').points.at(-1).value));await page.locator('#trend-search').fill('');await category('metal');assert.equal(await page.locator('#market-rows tr').count(),2);assert.match(await page.locator('#instrument-coverage').textContent(),/整月均价/);assert.match(await page.locator('#last-date').textContent(),/^\d{4}-\d{2}-01$/);
await category('all');await page.locator('#trend-search').fill('不存在');assert.equal(await page.locator('#market-rows tr').count(),0);assert.equal(await page.locator('#no-results').isVisible(),true);await page.locator('#trend-search').fill('EUR/USD');assert.equal(await page.locator('#market-rows tr').count(),1);await page.locator('#trend-search').fill('');
await category('housing');assert.equal(await page.locator('#housing-panel').isVisible(),true);assert.equal(await page.locator('#selected-instrument').isVisible(),false);assert.equal(await page.locator('#index-city option').count(),70);assert.equal(await page.locator('#index-paths path').count(),2);
await page.locator('#region-open').click();await page.locator('#region-province').selectOption('湖北');await page.locator('#region-city').fill('武汉');await page.locator('#region-district').fill('武昌区');await page.locator('#region-apply').click();assert.equal(await page.locator('#index-unavailable').isVisible(),true);assert.equal(await page.locator('#index-results').isVisible(),false);
await page.locator('#region-open').click();await page.locator('#region-city').fill('取消修改');await page.keyboard.press('Escape');assert.equal(await page.locator('#region-dialog').evaluate(d=>d.open),false);assert.match(await page.locator('#index-unavailable-reason').textContent(),/武昌区/);
await page.locator('#index-region-clear').click();await page.locator('#index-city').selectOption('上海');await page.locator('#index-kind').selectOption('resale');assert.equal(await page.locator('#index-value').textContent(),'100.3');await category('rent');await page.locator('#index-metric').selectOption('yoy');assert.equal(await page.locator('#index-value').textContent(),'-0.6%');assert.equal(await page.locator('#index-unit').textContent(),'全国 CPI 分项（%）');
await category('fx');if(viewport.width<=760)await page.locator('#mobile-sort').selectOption('change-desc');else await page.locator('[data-sort="change"]').click();const row1=await page.locator('#market-rows tr').first().textContent();if(viewport.width<=760)await page.locator('#mobile-sort').selectOption('change-asc');else await page.locator('[data-sort="change"]').click();assert.notEqual(await page.locator('#market-rows tr').first().textContent(),row1);
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await page.screenshot({path:`/tmp/ai014-produce-${viewport.width}.png`,fullPage:true});
assert.deepEqual(errors,[]);await context.close();console.log(`PASS ${viewport.width}: categories, true charts, ranges, observation slider, persistent favorites, search, missing states, region Apply/Escape, sorting, no overflow/errors`);
}
await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
